[workspace]
members = ["torrent"]

[package]
name = "media-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
axum = { version = "0.7.5", features = ["macros", "tracing"] }
axum-extra = { version = "0.9.3", features = ["typed-header"] }
base64 = "0.22.0"
bytes = "1.6.0"
clap = { version = "4.5.3", features = ["derive"] }
crc32fast = { version = "1.4.0", features = ["nightly"] }
dirs = "5.0.1"
dotenvy = "0.15.7"
notify = { version = "6.1.1", default-features = false, features = ["macos_kqueue"] }
rand = "0.8.5"
reqwest = { version = "0.12.1", features = ["json"] }
serde = { version = "1.0.197", features = ["serde_derive"] }
serde_json = "1.0.114"
sha2 = "0.10.8"
sqlx = { version = "0.7.4", features = ["runtime-tokio", "macros", "time", "uuid", "sqlite"] }
time = { version = "0.3.34", features = ["serde", "parsing"] }
tokio = { version = "1.36.0", features = ["full"] }
tokio-stream = { version = "0.1.15", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["full"] }
toml = "0.8.12"
tower-http = { version = "0.5.2", features = ["cors", "fs"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["json", "serde_json", "serde", "time", "fmt", "env-filter"] }
uuid = { version = "1.6.1", features = ["v4", "serde"] }
torrent = {path = "./torrent"}
tray-icon = "0.13.4"
open = "5.1.2"
image = "0.25.1"

[target.'cfg(windows)'.dependencies]
winit = "0.29.15"
