[workspace]
members = [".", "torrent", "upnp"]

[package]
name = "media-server"
version = "0.1.0"
edition = "2021"

[features]
windows-tray = ["dep:tray-icon", "dep:open", "dep:image", "dep:winit"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
tokio = { version = "1.42.0", features = ["full", "tracing"] }
tokio-util = { version = "0.7.13", features = ["full"] }
anyhow = "1.0.93"
axum = { version = "0.7.9", features = ["macros", "tracing", "multipart"] }
axum-extra = { version = "0.9.6", features = ["typed-header"] }
time = { version = "0.3.37", features = ["serde", "parsing"] }
tracing = "0.1.41"
uuid = { version = "1.11.0", features = ["v4", "serde"] }
reqwest = { version = "0.12.12", features = ["json", "stream"] }
serde = { version = "1.0.217", features = ["serde_derive"] }
rand = "0.8.5"
lru = "0.12.5"
sysinfo = "0.33.1"

[dependencies]
tokio = { workspace = true, features = ["full", "tracing"] }
tokio-util = { workspace = true, features = ["full"] }
anyhow = { workspace = true }
axum = { workspace = true, features = ["macros", "tracing", "multipart"] }
axum-extra = { workspace = true, features = ["typed-header"] }
time = { workspace = true, features = ["serde", "parsing"] }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v4", "v1", "serde"] }
reqwest = { workspace = true, features = ["json", "stream"] }
serde = { workspace = true, features = ["serde_derive"] }
rand = { workspace = true }
lru = { workspace = true }
sysinfo = { workspace = true }
base64 = "0.22.1"
bytes = "1.8.0"
clap = { version = "4.5.23", features = ["derive"] }
crc32fast = { version = "1.4.2", features = ["nightly"] }
dirs = "5.0.1"
dotenvy = "0.15.7"
notify = { version = "7.0.0", default-features = false, features = ["macos_kqueue"] }
serde_json = "1.0.134"
sha2 = "0.10.8"
sqlx = { version = "0.8.2", features = ["runtime-tokio", "macros", "time", "uuid", "sqlite"] }
tokio-stream = { version = "0.1.17", features = ["full"] }
toml = "0.8.19"
tower-http = { version = "0.6.2", features = ["cors", "fs"] }
tracing-subscriber = { version = "0.3.19", features = ["json", "serde_json", "serde", "time", "fmt", "env-filter"] }
utoipa = { version = "5.2.0", features = ["axum_extras", "time", "url", "uuid"] }
utoipa-swagger-ui = { version = "8.0.3", features = ["axum"] }
serde_plain = "1.0.2"
toml_edit = { version = "0.22.22", features = ["serde"] }
symphonia = { version = "0.5.4", features = ["all"] }
mp4 = "0.14.0"
bitvec = "1.0.1"
test-log = "0.2.16"
torrent = { path = "./torrent" }
upnp = { path = "./upnp" }

# Windows dependencies
tray-icon = { version = "0.17.0", optional = true }
open = { version = "5.3.0", optional = true }
image = { version = "0.25.2", optional = true }
winit = { version = "0.30.5", optional = true }
