name: Rust CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: "sqlite:database.sqlite"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4    
    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        ffmpeg \
        pkg-config \
        libavcodec-dev \
        libavformat-dev \
        libavfilter-dev \
        libavutil-dev \
        libavdevice-dev \
        libswscale-dev
    - name: Check spelling
      uses: crate-ci/typos@master
    - name: Rust setup
      run: rustup toolchain install nightly --profile minimal
    - name: Set rust nightly
      run: rustup default nightly
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Install sqlx-cli
      run: cargo install sqlx-cli
    - name: Create database file
      run: sqlx database create
    - name: Run migrations
      run: sqlx migrate run
    - name: Check code formatting
      run: cargo fmt --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
