name: pipeline
on:
 push:
   branches:
     - "dev"

permissions:
  packages: write
  contents: read

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            dog4ik/media-server:latest
            dog4ik/media-server:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    environment: CI
    needs:
      - build-and-push-image
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: create env file
      run: |
        echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile

    - name: Docker Stack Deploy
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: deploy
        key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}
        port: ${{ secrets.DEPLOY_SSH_PORT }}
        script: docker stack deploy -c demo.docker.stack.yaml provod-demo-stack
